### PR TITLE
Add platform forwarders for String#toLowerCase(Locale.ENGLISH)

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by cquiroz** [comment]
I was thinking exactly on a solution like this. This assumes scala.js `lowerCase` goes to english which is a bit iffy since it goes to the native `lowerCase`. I think it will work correctly but perhaps a test with `tr` locale would be good

**Comment by soc** [comment]
I had a look in the ECMA spec, it's specified there that it's locale-independent. We would only need to adjust the code if Scala.js decided to make their `toLowerCase` behave more like the JVM one, and less like the JS one.
I think this wouldn't be a huge issue, as we could just call the JS one directly, instead of going through the convenient Scala.js wrapper.

(Actually, maybe it would be more correct if Scala.js' `toLowerCase` would call JS' `toLocaleLowerCase` ...)

**Comment by mkotsbak** [comment]
Yes, I agree that it probably should call toLocaleLowerCase to replicate the jvm using current locale.

**Comment by mkotsbak** [comment]
Yes, I agree that it probably should call toLocaleLowerCase to replicate the jvm using current locale. 

And yes, users of sjs expected behavior to be more like Scala on jvm than JS.

**Comment by mkotsbak** [comment]
Forget my last commit. That applies to the sjs String.toLowercase and should instead be treated as a sjs bug.

**Comment by cquiroz** [comment]
To me is very strange that `toLocaleLowerCase` talks about the environment's `Locale` but I haven't found how and where that locale is defined

**Comment by mkotsbak** [comment]
I think it is the preferred language set in the browser. For Node.js maybe it reads it from the environment. I registered it as a bug in SJS: https://github.com/scala-js/scala-js/issues/2551

**Comment by mkotsbak** [comment]
It did not work in the sense that it used the default locale English instead of my browser's preferred language. For features supported by JS I think we should use those instead of using the default locale.

**Comment by soc** [comment]
@cquiroz Yeah, it's basically the browser's decision. As a developer you can't tell it the locale you want, its locale is whatever some browser on a user machine decides.

**Pull request merged**
