### PR TITLE
ServiceLoader: platform-dependent implementations and forwarders

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by cquiroz** [comment]
So we disabled loading zones and chronologies on runtime on scala.js right?

**Comment by soc** [comment]
Yes, this is just a first prototype that exposes the extension points. We can wire things up later at these places, but for now the code looking for non-existing stuff doesn't crash on JS anymore.

**Comment by cquiroz** [comment]
looks good

**Comment by soc** [comment]
Thanks!

**Pull request merged**
